### ISSUE TITLE
Unexpected error.

### ISSUE THREAD

**Issue by fieldju** [GiG/rollup-plugin-rename-extensions#2]
I am seeing the following stack trace, when trying to apply this plugin to a second, project.

```
[!] (rename-rollup plugin) TypeError: baseVisitor[type] is not a function
TypeError: baseVisitor[type] is not a function
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.skipThrough (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:182:37)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.base.NewExpression.base.CallExpression (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:341:3)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.skipThrough (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:182:37)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.base.MemberExpression (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:347:3)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.skipThrough (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:182:37)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.base.NewExpression.base.CallExpression (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:341:3)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.skipThrough (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:182:37)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.base.MemberExpression (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:347:3)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.skipThrough (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:182:37)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.base.NewExpression.base.CallExpression (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:341:3)
    at c (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:23:22)
    at Object.skipThrough (/Users/jfiel2/dev/spinnaker/deck/app/scripts/modules/core/node_modules/acorn-walk/src/index.js:182:37)

error Command failed with exit code 1.
```

interestingly enough this plugin works just fine in the first project I applied it to.

Here is the relevant section my my rollup config

```
  input: [webpackConfig.entry.lib],
  output: { name: 'core', dir: 'lib/', format: 'es', sourcemap: true },
  treeshake: true,
  preserveModules: true,
  plugins: [
    renameExtensions({
      include: ['**/*.ts', '**/*.tsx'],
      mappings: {
        '.ts': '.js',
        '.tsx': '.js',
      }
    }),
```

I doubt this is enough information to be useful, but I will create the issue anyways and attach a remote debugger in the morning.

Cheers,

Justin

**Comment by TomCaserta** [comment]
Hey I'll take a look later today. I think the issue may be that the library I'm using to simplify walking over the AST (acorn ewalk) doesn't support the target your typescript is outputting. 

I'll need to replace it to get it to work. ( You can try changing the target in tsconfig if that's doable for your codebase but I guess that would defeat the purpose of you're outputting modules.)
